### ISSUE TITLE
help

### ISSUE THREAD

**Issue by whoami-gzc** [Kfor/questionnaire#2]
是直接用npm启动前端吗？

**Comment by Kfor** [comment]
对的，在frontend路径下npm install后npm run serve

**Comment by whoami-gzc** [comment]
谢谢，项目已经启动了，感谢你的分享




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kfor/questionnaire"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月4日(星期五) 上午10:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kfor/questionnaire] help (#2)





 
对的，在frontend路径下npm install后npm run serve
