### ISSUE TITLE
跪求sql

### ISSUE THREAD

**Issue by songlin12** [Kfor/questionnaire#6]
大哥，又没有sql脚本呀

**Comment by Kfor** [comment]
直接运行即可，表是后端自动创建的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 天明 ***@***.***&gt;
发送时间: 2023年4月14日 15:35
收件人: Kfor/questionnaire ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Kfor/questionnaire] 跪求sql (Issue #6)





 
大哥，又没有sql脚本呀

**Comment by songlin12** [comment]
哦哦，没用过Hibernate
